#!/bin/bash


#+-------------------+
#+---"Main Script"---+
#+-------------------+
verbosity=6
while_type="NEW"
source /usr/local/bin/helper_script.sh
source /usr/local/bin/config.sh
edebug "inotify_music_handler started"
watch_folder="${flaclibrary_source%/*}"
edebug "watch_folder will be $watch_folder"
inotifywait -m -r "$watch_folder" -e create -e moved_to --format="%e %w%f" |
while read -r action fullpath; do
  if [[ "$fullpath" =~ .*syncme$ ]]; then # Does the file end with .syncme?
    echo "action is:${action}, file is:${fullpath}, exporting now"
    export SYNCME_SOURCE_DIR="${fullpath%/*}"
    export SYNCME_ACTION="${action}"
    export WHILE_TYPE="$while_type"
    /usr/local/bin/inotify_music_processor
  fi
done