#!/usr/bin/env bash

# (C) 2022 littlejeem
# https://github.com/littlejeem

# This code is licensed under MIT license:
# http://opensource.org/licenses/MIT

# Shell Style Guide have been adhered to where viable
# https://google.github.io/styleguide/shell.xml
# and
# https://tldp.org/LDP/abs/html/index.html

# Linted with shellcheck: https://github.com/koalaman/shellcheck

# Developed using Atom: https://atom.io/

# References:
# HERE IF APLICABLE

# Credits
# Thank you to anyone who has made script, posted on stackexchange or posted a blog thats influenced me,
# if i've used something and not credited message me and I'll add it. ta!

# DISCLAIMER
# Whilst care has been taken to thoroughly test this script, my knowledge is currently limited to Ubuntu
# cases, # as with all Linux/UNIX-like affairs, it may still fail in mysterious
# circumstances. I'M STILL A NEWB!

#########################################################################
###    "PUT INFO ABOUT THE SCRIPT, ITS PURPOSE, HOW IT WORKS"         ###
###      "WHERE IT SHOULD BE KEPT, DEPENDANCIES, etc...here"          ###
#########################################################################

#+--------------------------------------+
#+---"Exit Codes & Logging Verbosity"---+
#+--------------------------------------+
# Exit codes:
# pick from 64 - 113 (https://tldp.org/LDP/abs/html/exitcodes.html#FTN.AEN23647)
# exit 0 = Success
# exit 64 = Variable Error
# exit 65 = Sourcing file/folder error
# exit 66 = Processing Error
# exit 67 = Required Program Missing

# Verbosity levels
# silent_lvl=0
# crt_lvl=1
# err_lvl=2
# wrn_lvl=3
# ntf_lvl=4
# inf_lvl=5
# dbg_lvl=6


#+----------------------+
#+---"Notes on style"---+
#+----------------------+
# Use one return to seperate chunks of code from each other
# Use two returns to seperate sections in the script
# Use #+------+ to header sections
# Use ########
#     ###  ###
#     ######## to indicate important fill-in sections

# Two spaces to indent, NOT TABS!

# don't echo "" or echo -e "" for a blank line, use echo -e "\r" or echo -e "\n"
# edebug "\r" or equivalent will also work

# Todo example
# TODO(littlejeem): Handle the unlikely edge cases (bug ####)

# Google style guide states that a function uses the format 'function name () {' style to declare a function
# but commonly accepted practice is that function is no longer used and depricated so plain 'name () {'
# Use comments to describe inobvious functions, example below

#######################################
# Cleanup files from the backup directory.
# Globals:
#   BACKUP_DIR
#   ORACLE_SID
# Arguments:
#   None
#######################################

# the help function in this file needs no comments as its usage is straight forward


#+----------------------+
#+---"Check for Root"---+
#+----------------------+
#only needed if root privaleges necessary, enable
#if [[ $EUID -ne 0 ]]; then
#    echo "Please run this script with sudo:"
#    echo "sudo $0 $*"
#    exit 66
#fi
#
#
#+-----------------------+
#+---"Set script name"---+
#+-----------------------+
# imports the name of this script
# failure to to set this as lockname will result in check_running failing and 'hung' script
# manually set this if being run as child from another script otherwise will inherit name of calling/parent script
scriptlong=$(basename "$0")
#test to see if ends in .sh, if so remove
if [[ "${scriptlong#"${scriptlong%???}"}" == ".sh" ]]; then
  lockname=${scriptlong::-3}
else
  lockname="$scriptlong"
fi
#
#
#+--------------------------+
#+---Source helper script---+
#+--------------------------+
source /usr/local/bin/helper_script.sh
#
#
#+---------------------+
#+---"Set Variables"---+
#+---------------------+
#set default logging level, failure to set this will cause a 'unary operator expected' error
#remember at level 3 and lower, only esilent messages show, best to include an override in getopts
verbosity=3
#
version="0.3" #
script_pid=$(echo $$)
stamp=$(echo "$(date +%H%M)_$(date +%d%m%Y)")
notify_lock=/tmp/${scriptlong}_notify
#pushover_title="NAME HERE" #Uncomment if using pushover


#+-------------------+
#+---Set functions---+
#+-------------------+
helpFunction () {
   echo ""
   echo "Usage: $0 $scriptlong"
   echo "Usage: $0 $scriptlong -G"
   echo -e "\t Running the script with no flags causes default behaviour with logging level set via 'verbosity' variable"
   echo -e "\t-S Override set verbosity to specify silent log level"
   echo -e "\t-V Override set verbosity to specify Verbose log level"
   echo -e "\t-G Override set verbosity to specify Debug log level"
   echo -e "\t-h Use this flag for help"
   if [ -d "/tmp/$lockname" ]; then
     edebug "removing lock directory"
     rm -r "/tmp/$lockname"
   else
     edebug "problem removing lock directory"
   fi
   exit 65 # Exit script after printing help
}

clean_ctrlc () {
  let ctrlc_count++
  if [[ $ctrlc_count == 1 ]]; then
    echo "Quit command detected, are you sure?"
  elif [[ $ctrlc_count == 2 ]]; then
    echo "...once more and the script will exit..."
  else
    echo "...exiting script."
    if [ -d "/tmp/$lockname" ]; then
      edebug "removing lock directory"
      rm -r "/tmp/$lockname"
    else
      edebug "problem removing lock directory"
    fi
  fi
  exit 66
}

clean_exit () {
  if [ -d "/tmp/$lockname" ]; then
    edebug "removing lock directory"
    rm -r "/tmp/$lockname"
  else
    edebug "problem removing lock directory"
  fi
  esilent "$lockname completed"
  exit 0
}

#+------------------------+
#+---"Get User Options"---+
#+------------------------+
OPTIND=1
while getopts ":SVGHh:" opt
do
    case "${opt}" in
        S) verbosity=$silent_lvl
        edebug "-S specified: Silent mode";;
        V) verbosity=$inf_lvl
        edebug "-V specified: Verbose mode";;
        G) verbosity=$dbg_lvl
        edebug "-G specified: Debug mode";;
#Example for extra options
#        d) drive_install=${OPTARG}
#        edebug "-d specified: alternative drive being used";;
        H) helpFunction;;
        h) helpFunction;;
        ?) helpFunction;;
    esac
done
shift $((OPTIND -1))


#+---------------------+
#+---"Trap & ctrl-c"---+
#+---------------------+
#SIGINT, SIGTERM, or SIGHUP
trap clean_ctrlc SIGINT
trap clean_exit SIGTERM
ctrlc_count=0


#+---------------------------------------+
#+---"check if script already running"---+
#+---------------------------------------+
check_running


#+----------------------+
#+---"Script Started"---+
#+----------------------+
# At this point the script is set up and all necessary conditions met so lets log this
esilent "$scriptlong started"


#+-------------------------------+
#+---Configure GETOPTS options---+
#+-------------------------------+
#e.g for a drive option
edebug "GETOPTS options set"


#+--------------------------+
#+---"Source config file"---+
#+--------------------------+
#source /usr/local/bin/config.sh


#+--------------------------------------+
#+---"Display some info about script"---+
#+--------------------------------------+
edebug "Version of $scriptlong is: $version"
edebug "Version of helper_script is: $helper_version"
edebug "PID is $script_pid"


#+-------------------+
#+---Set up script---+
#+-------------------+
#Get environmental info
edebug "INVOCATION_ID is set as: $INVOCATION_ID"
edebug "EUID is set as: $EUID"
edebug "PATH is: $PATH"


#+----------------------------+
#+---"Main Script Contents"---+
#+----------------------------+
#TODO(littlejeem): Move variable into a section of /usr/bin/config
\\TODO
if grep -qs '//192.168.0.18/MUSICFILES' /proc/mounts; then
  edebug "Samba share located, updating..."
  mpc update --wait NAS/ > /dev/null
  edebug "...share updated"
else
  ecrit "Samba share non responsive, not updating"
  #Call pushover
  pushover_title="Volumio library update"
  #define $application_token and $user_token in config file (/usr/local/bin/config.sh)
  message_form="Automatic update failed, SAMBA share not detected"
  pushover
fi

#TODO(littlejeem): Any validity to using a different TEST to see is machine online?
#ping -c 4 192.168.0.18 2>&1 >/dev/null
#if [[ $? -eq 0 ]]; then
#  echo "DO MAIN SCRIPT"
#else
#  echo "ERROR! Server Source not found, no updating in case of issues"
#fi


#+----------------+
#+---"Pushover"---+
#+----------------+
#Call pushover
#pushover_title="My great script name, pushover message header"
#define $application_token and $user_token in config file (/usr/local/bin/config.sh)
#$message_form="Your main script message, usually errors not successes"
#pushover


#+-------------------+
#+---"Script Exit"---+
#+-------------------+
rm -r /tmp/"$lockname"
if [[ $? -ne 0 ]]; then
    eerror "error removing lockdirectory"
    exit 65
else
    enotify "successfully removed lockdirectory"
fi
esilent "$lockname completed"
exit 0